package  cdoclet.test{
	/**
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInClassBase.	 * Do not edit.
	 */
	[RemoteClass(alias="cdoclet.test.TestIgnoreInClassBase")]
	public class TestIgnoreInClassBase {
	}
}