package cdoclet.test{
	import cdoclet.test.TestProxyInterfaceGeneric;
	/**
	 * Generated by CDoclet from cdoclet.test.TestProxyInterfaceBase.	 * Do not edit.
	 */
	public interface TestProxyInterfaceBase extends  cdoclet.test.TestProxyInterfaceGeneric {
		override function foo(bar:Date):Array;
	}
}