package cdoclet.test{
	/**
	 * Generated by CDoclet from cdoclet.test.TestProxyInterfaceGeneric.	 * Do not edit.
	 */
	public interface TestProxyInterfaceGeneric {
		function foo(bar:String):void;
	}
}