

package expectations.java.test;
/**
 * Generated by CDoclet from TestIgnoreClass.
	 * Do not edit.
 */
public class TestIgnoreClass<T> {
	private T test;

	public T getTest() {
		return this.test;
	}

	public void setTest(T value) {
		this.test = value;
	}
}
