

package expectations.java.test;
/**
 * Generated by CDoclet from TestInterfaceGeneric.
	 * Do not edit.
 */
public interface TestInterfaceGeneric<A extends java.util.Date, B> {
	void foo(A bar, B baz);
}
