

package test;
/**
 * Generated by CDoclet from test.TestException. Do not edit.
 */
public class TestException extends Exception {
	
	public TestException() {
	}
	
	public TestException(String message) {
		super(message);
	}
	
	public TestException(Throwable cause) {
		super(cause);
	}
	
	public TestException(String message, Throwable cause) {
		super(message, cause);
	}
}
