

package test;
/**
 * Generated by CDoclet from test.TestClassAnnotations. Do not edit.
 */
@Deprecated
public class TestClassAnnotations {
	private String annotatedProperty;
	private String notAnnotatedProperty;
	
	@Deprecated
	public String getAnnotatedProperty() {
		return this.annotatedProperty;
	}
	
	@Deprecated
	public void setAnnotatedProperty(String value) {
		this.annotatedProperty = value;
	}
	
	public String getNotAnnotatedProperty() {
		return this.notAnnotatedProperty;
	}
	
	public void setNotAnnotatedProperty(String value) {
		this.notAnnotatedProperty = value;
	}
}
