

package test;
/**
 * Generated by CDoclet from test.TestIgnoreInClass.	 * Do not edit.
 */
public class TestIgnoreInClass<T> extends test.TestIgnoreInClassBase<T> {
	
	@Override
	public T getTest() {
		return super.getTest();
	}
	
	@Override
	public void setTest(T value) {
		super.setTest(value);
	}
}
