

package test;
/**
 * Generated by CDoclet from test.TestProxyInterfaceBase.	 * Do not edit.
 */
public interface TestProxyInterfaceBase<T extends java.util.Date> extends test.TestProxyInterfaceGeneric {
	java.util.Collection<T> foo(T bar);
}
