

package test;
/**
 * Generated by CDoclet from test.TestOverrideClassBase. Do not edit.
 */
public class TestOverrideClassBase<T> implements test.TestOverrideInterface<T> {
	private T test;
	
	public T getTest() {
		return this.test;
	}
	
	public void setTest(T value) {
		this.test = value;
	}
}
