

package expectations.java.test;
/**
 * Generated by CDoclet from TestIgnoreInInterface.
	 * Do not edit.
 */
public interface TestIgnoreInInterface<T> extends TestIgnoreInInterfaceBase<T> {
	T getTest();
	void testMethod();
}
