

package test;
/**
 * Generated by CDoclet from test.TestInterfaceAnnotations. Do not edit.
 */
@Deprecated
public interface TestInterfaceAnnotations {
	@Deprecated
	void annotatedMethod();
	void notAnnotatedMethod();
}
