

package test;
/**
 * Generated by CDoclet from test.TestOverrideInterface.	 * Do not edit.
 */
public interface TestOverrideInterface<T> extends test.TestOverrideInterfaceBase<T> {
	T getTest();
	void testMethod();
}
