

package expectations.java.test;

import java.sql.Date;

/**
 * Generated by CDoclet from TestProxyInterface.
	 * Do not edit.
 */
public interface TestProxyInterface extends TestProxyInterfaceBase<Date> {
}
