

package test;
/**
 * Generated by CDoclet from test.TestIgnoreInClassBase.	 * Do not edit.
 */
public class TestIgnoreInClassBase<T> extends test.TestOverrideClassBase<T> {
	
	@Override
	public T getTest() {
		return super.getTest();
	}
	
	@Override
	public void setTest(T value) {
		super.setTest(value);
	}
}
