

package test;
/**
 * Generated by CDoclet from test.TestIgnoreInInterface. Do not edit.
 */
public interface TestIgnoreInInterface<T> extends test.TestIgnoreInInterfaceBase<T> {
	T getTest();
	void testMethod();
}
