

package test;
/**
 * Generated by CDoclet from test.TestOverrideBean. Do not edit.
 */
public class TestOverrideBean extends test.TestBean {
	private long count;
	
	public long getCount() {
		return this.count;
	}
	
	public void setCount(long value) {
		this.count = value;
	}
}
