

package test;
/**
 * Generated by CDoclet from test.TestBeanWithBoolean.	 * Do not edit.
 */
public class TestBeanWithBoolean {
	private boolean valid;
	
	public boolean isValid() {
		return this.valid;
	}
	
	public void setValid(boolean value) {
		this.valid = value;
	}
}
