

package test;
/**
 * Generated by CDoclet from test.TestIgnoreInterface. Do not edit.
 */
public interface TestIgnoreInterface<T> extends test.TestOverrideInterfaceBase<T> {
	T getTest();
	void testMethod();
}
