

package expectations.java.test;
/**
 * Generated by CDoclet from TestOverrideClass.
	 * Do not edit.
 */
public class TestOverrideClass<T> extends TestOverrideClassBase<T> {

	@Override
	public T getTest() {
		return super.getTest();
	}

	@Override
	public void setTest(T value) {
		super.setTest(value);
	}
}
