

package test;
/**
 * Generated by CDoclet from test.TestProxyInterface. Do not edit.
 */
public interface TestProxyInterface extends test.TestProxyInterfaceBase<java.sql.Date> {
    String NAME = "test";

	void baz(long ago);
}
