

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestOverrideClass.	 * Do not edit.
	 * </summary>
	 */
	public class TestOverrideClass<T> : asdoclet.test.TestOverrideClassBase<T> {
		private T test;
		public override T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}