

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInInterface.	 * Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterface<T> : asdoclet.test.TestIgnoreInInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}