

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestOverrideInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestOverrideInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}