

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestProxyInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterfaceBase<T> : asdoclet.test.TestProxyInterfaceGeneric where T : System.DateTime? {
		System.Collections.Generic.ICollection<T> Foo(T bar);
	}
#endregion
}