

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestInterfaceGeneric.	 * Do not edit.
	 * </summary>
	 */
	public interface TestInterfaceGeneric<A, B> where A : System.DateTime? {
		void Foo(A bar, B baz);
	}
#endregion
}