

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterfaceBase<T> {
	}
#endregion
}