

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreGeneric.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreGeneric : asdoclet.test.TestOverrideClass {
	}
#endregion
}