

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestProxyInterfaceGeneric.	 * Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterfaceGeneric {
		void Foo(string bar);
	}
#endregion
}