

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestProxyInterface.	 * Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterface : asdoclet.test.TestProxyInterfaceBase<java.sql.Date> {
	}
#endregion
}