

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInClass.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreInClass<T> : asdoclet.test.TestIgnoreInClassBase<T> {
		private T test;
		public virtual T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}