

namespace asdoclet.test {
#region AsDoclet generated code
	/**
	 * <summary>
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInClassBase.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreInClassBase<T> {
	}
#endregion
}