package cdoclet.test{
	import cdoclet.test.TestIgnoreInInterfaceBase;
	/**
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInInterface.	 * Do not edit.
	 */
	public interface TestIgnoreInInterface extends  cdoclet.test.TestIgnoreInInterfaceBase {
		function getTest():Object;
		function testMethod():void;
	}
}