package cdoclet.test{
	import cdoclet.test.TestProxyInterfaceBase;
	/**
	 * Generated by CDoclet from cdoclet.test.TestProxyInterface.	 * Do not edit.
	 */
	public interface TestProxyInterface extends  cdoclet.test.TestProxyInterfaceBase {
	}
}