package  cdoclet.test{
	import cdoclet.test.TestOverrideClass;
	/**
	 * Generated by CDoclet from cdoclet.test.TestIgnoreGeneric.	 * Do not edit.
	 */
	[RemoteClass(alias="cdoclet.test.TestIgnoreGeneric")]
	public class TestIgnoreGeneric extends cdoclet.test.TestOverrideClass  {
	}
}