package cdoclet.test{
	import cdoclet.test.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from cdoclet.test.TestOverrideInterface.	 * Do not edit.
	 */
	public interface TestOverrideInterface extends  cdoclet.test.TestOverrideInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}