

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestOverrideClass. Do not edit.
	 * </summary>
	 */
	public class TestOverrideClassDto<T> : testcs.TestOverrideClassBase<T> {
		public override T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}
