

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestException. Do not edit.
	 * </summary>
	 */
	public class TestExceptionDto : System.Exception {
		public  TestExceptionDto()  : base() {}
		public  TestExceptionDto(string message)  : base(message) {}
		public  TestExceptionDto(string message, System.Exception exception)  : base(message, exception) {}
	}
#endregion
}