

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestBean. Do not edit.
	 * </summary>
	 */
	public class TestBeanDto {
		private int value;
		private string name;
		private testcs.TestBeanDto self;
		public virtual int Value { get { return this.value; } set { this.value = value; } }
		public virtual string Name { get { return this.name; } set { this.name = value; } }
		public virtual testcs.TestBeanDto Self { get { return this.self; } set { this.self = value; } }
	}
#endregion
}
