

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreInInterface. Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterface<T> : testcs.TestIgnoreInInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}