

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestOverrideClassBase. Do not edit.
	 * </summary>
	 */
	public class TestOverrideClassBaseDto<T> : testcs.TestOverrideInterface<T> {
		private T test;
		public virtual T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}