

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestEnum. Do not edit.
	 * </summary>
	 */
	public enum TestEnum {
		Right, 
		Middle, 
		Left
	}
#endregion
}
