

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestProxyInterfaceBase. Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterfaceBase<T> : testcs.TestProxyInterfaceGeneric where T : System.DateTime? {
		System.Collections.Generic.ICollection<T> Foo(T bar);
	}
#endregion
}
