

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreGeneric. Do not edit.
	 * </summary>
	 */
	public class TestIgnoreGenericDto : testcs.TestOverrideClass<testcs.TestExceptionDto> {
	}
#endregion
}
