

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestOverrideInterface. Do not edit.
	 * </summary>
	 */
	public interface TestOverrideInterface<T> : testcs.TestOverrideInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}
