

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestClassAnnotations. Do not edit.
	 * </summary>
	 */
	[System.Obsolete]
	[System.Serializable]
	public class TestClassAnnotationsDto {
		private string annotatedProperty;
		private string notAnnotatedProperty;
		[System.Obsolete]
		[System.Serializable]
		public virtual string AnnotatedProperty { get { return this.annotatedProperty; } set { this.annotatedProperty = value; } }
		public virtual string NotAnnotatedProperty { get { return this.notAnnotatedProperty; } set { this.notAnnotatedProperty = value; } }
	}
#endregion
}