

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestProxyInterface. Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterface : testcs.TestProxyInterfaceBase<java.sql.Date> {
		void Baz(AsyncCallback async, long ago);
	}
#endregion
}