

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreInInterfaceBase. Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterfaceBase<T> : testcs.TestOverrideInterfaceBase<T> {
	}
#endregion
}
