

namespace testcs {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TästBean. Do not edit.
	 * </summary>
	 */
	public class TästBeanDto {
		private int Välue;
		private string Näme;
		private testcs.TestBeanDto self;
		public virtual int Välue { get { return this.Välue; } set { this.Välue = value; } }
		public virtual string Näme { get { return this.Näme; } set { this.Näme = value; } }
		public virtual testcs.TestBeanDto Self { get { return this.self; } set { this.self = value; } }
	}
#endregion
}
