

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInClass.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreInClass<T> : cdoclet.test.TestIgnoreInClassBase<T> {
		public override T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}