

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestOverrideClass. Do not edit.
	 * </summary>
	 */
	public class TestOverrideClass<T> : test.TestOverrideClassBase<T> {
		public override T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}