

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreInterface. Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInterface<T> : test.TestOverrideInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}