

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestOverrideInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestOverrideInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}