

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreGeneric. Do not edit.
	 * </summary>
	 */
	public class TestIgnoreGeneric : test.TestOverrideClass<test.TestException> {
	}
#endregion
}