

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreInInterface.	 * Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterface<T> : test.TestIgnoreInInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}