

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreClass.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreClass<T> : test.TestOverrideClassBase<T> {
		public override T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}