

namespace test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from test.TestIgnoreInInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterfaceBase<T> : test.TestOverrideInterfaceBase<T> {
	}
#endregion
}