

    /**
     * Generated by CDoclet from test.TestClassAnnotations.	 * Do not edit.
     */
    function TestClassAnnotations() {
		this.annotatedProperty;
		this.notAnnotatedProperty;
    }
