

    /**
     * Generated by CDoclet from test.TestClassAnnotations.	 * Do not edit.
     */
    function TestClassAnnotations() {
		var annotatedProperty;
		var notAnnotatedProperty;
    }
