

    /**
     * Generated by CDoclet from test.TestEnum.	 * Do not edit.
     */
    function TestEnum() {}

    TestEnum.prototype.Right = "Right";
    TestEnum.prototype.Middle = "Middle";
    TestEnum.prototype.Left = "Left";

