

package testjava;
/**
 * Generated by CDoclet from test.AbstractTestBean. Do not edit.
 */
public abstract class AbstractTestBeanDto {
	private int value;
	private String name;
	private testjava.TestBean self;
	
	public int getValue() {
		return this.value;
	}
	
	public void setValue(int value) {
		this.value = value;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String value) {
		this.name = value;
	}
	
	public testjava.TestBean getSelf() {
		return this.self;
	}
	
	public void setSelf(testjava.TestBean value) {
		this.self = value;
	}
}
