

package testjava;
/**
 * Generated by CDoclet from test.TestProxyInterfaceBase. Do not edit.
 */
public interface TestProxyInterfaceBase<T extends java.util.Date> extends testjava.TestProxyInterfaceGeneric {
	java.util.Collection<T> foo(T bar);
}
