

package testjava;
/**
 * Generated by CDoclet from test.TestProxyInterface. Do not edit.
 */
public interface TestProxyInterface extends testjava.TestProxyInterfaceBase<java.sql.Date> {
    String NAME = "test";

	testjava.TestBeanDto baz(long ago);
}
