

package testjava;
/**
 * Generated by CDoclet from test.TestOverrideClass. Do not edit.
 */
public class TestOverrideClassDto<T> extends testjava.TestOverrideClassBase<T> {
	
	@Override
	public T getTest() {
		return super.getTest();
	}
	
	@Override
	public void setTest(T value) {
		super.setTest(value);
	}
}
