

package testjava;
/**
 * Generated by CDoclet from test.TestBean. Do not edit.
 */
public class TestBeanDto {
	private int value;
	private String name;
	
	public int getValue() {
		return this.value;
	}
	
	public void setValue(int value) {
		this.value = value;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setName(String value) {
		this.name = value;
	}
}
