

package testjava;
/**
 * Generated by CDoclet from test.TestIgnoreInClass. Do not edit.
 */
public class TestIgnoreInClassDto<T> extends testjava.TestIgnoreInClassBase<T> {
	
	@Override
	public T getTest() {
		return super.getTest();
	}
	
	@Override
	public void setTest(T value) {
		super.setTest(value);
	}
}
