

package testjava;
/**
 * Generated by CDoclet from test.TestOverrideInterface. Do not edit.
 */
public interface TestOverrideInterface<T> extends testjava.TestOverrideInterfaceBase<T> {
	T getTest();
	void testMethod();
}
