

package testjava;
/**
 * Generated by CDoclet from test.TestException. Do not edit.
 */
public class TestExceptionDto extends Exception {
	
	public TestExceptionDto() {
	}
	
	public TestExceptionDto(String message) {
		super(message);
	}
	
	public TestExceptionDto(Throwable cause) {
		super(cause);
	}
	
	public TestExceptionDto(String message, Throwable cause) {
		super(message, cause);
	}
}
