

package testjava;
/**
 * Generated by CDoclet from test.TästBean. Do not edit.
 */
public class TästBeanDto {
	private int Välue;
	private String Näme;
	private testjava.TestBeanDto self;
	
	public int getVälue() {
		return this.Välue;
	}
	
	public void setVälue(int value) {
		this.Välue = value;
	}
	
	public String getNäme() {
		return this.Näme;
	}
	
	public void setNäme(String value) {
		this.Näme = value;
	}
	
	public testjava.TestBeanDto getSelf() {
		return this.self;
	}
	
	public void setSelf(testjava.TestBeanDto value) {
		this.self = value;
	}
}
