

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInInterfaceBase<T> {
	}
#endregion
}