

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInterface.	 * Do not edit.
	 * </summary>
	 */
	public interface TestIgnoreInterface<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}