

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestProxyInterfaceBase.	 * Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterfaceBase<T> : cdoclet.test.TestProxyInterfaceGeneric where T : System.DateTime? {
		System.Collections.Generic.ICollection<T> Foo(T bar);
	}
#endregion
}