

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestInterfaceAnnotations.	 * Do not edit.
	 * </summary>
	 */
	[System.Obsolete]
	[System.Serializable]
	public interface TestInterfaceAnnotations {
      [System.Obsolete]
      [System.Serializable]
		void AnnotatedMethod();
		void NotAnnotatedMethod();
	}
#endregion
}