

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestOverrideInterface.	 * Do not edit.
	 * </summary>
	 */
	public interface TestOverrideInterface<T> : cdoclet.test.TestOverrideInterfaceBase<T> {
		T GetTest();
		void TestMethod();
	}
#endregion
}