

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestIgnoreGeneric.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreGeneric : cdoclet.test.TestOverrideClass {
	}
#endregion
}