

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestProxyInterfaceGeneric.	 * Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterfaceGeneric {
		void Foo(string bar);
	}
#endregion
}