package  test{
	import test.TestOverrideClass;
	/**
	 * Generated by CDoclet from test.TestIgnoreGeneric. Do not edit.
	 */
	[RemoteClass(alias="test.TestIgnoreGeneric")]
	public class TestIgnoreGeneric extends test.TestOverrideClass  {
	}
}