package  test{
	import test.TestIgnoreInClassBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInClass. Do not edit.
	 */
	[RemoteClass(alias="test.TestIgnoreInClass")]
	public class TestIgnoreInClass extends test.TestIgnoreInClassBase  {
		private var _test:Object;
		public override function get test():Object {
			return _test;
		}
		public override function set test(value:Object):void {
			_test=value;
		}
	}
}