package  test{
	import test.TestOverrideInterface;
	/**
	 * Generated by CDoclet from test.TestOverrideClassBase. Do not edit.
	 */
	[RemoteClass(alias="test.TestOverrideClassBase")]
	public class TestOverrideClassBase implements test.TestOverrideInterface {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}