package test{
	import test.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInInterfaceBase. Do not edit.
	 */
	public interface TestIgnoreInInterfaceBase extends  test.TestOverrideInterfaceBase {
	}
}