package test{
	/**
	 * Generated by CDoclet from test.TestInterfaceAnnotations.	 * Do not edit.
	 */
	[Deprecated]
	[Bindable]
	public interface TestInterfaceAnnotations {
		[Deprecated]
		[Bindable]
		function annotatedMethod():void;
		function notAnnotatedMethod():void;
	}
}