package test{
	/**
	 * Generated by CDoclet from test.TestOverrideInterfaceBase. Do not edit.
	 */
	public interface TestOverrideInterfaceBase {
		function getTest():Object;
		function testMethod():void;
	}
}