package test{
	import test.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestOverrideInterface. Do not edit.
	 */
	public interface TestOverrideInterface extends  test.TestOverrideInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}