package  expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestOverrideClass;
	/**
	 * Generated by CDoclet from TestIgnoreGeneric.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestIgnoreGeneric")]
	public class TestIgnoreGeneric extends cdoclet.test.TestOverrideClass  {
	}
}
