package  expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestIgnoreInClassBase.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestIgnoreInClassBase")]
	public class TestIgnoreInClassBase {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}
