package test{
	import test.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInterface.	 * Do not edit.
	 */
	public interface TestIgnoreInterface extends  test.TestOverrideInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}