package expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestOverrideInterfaceBase.
	 * Do not edit.
	 */
	public interface TestOverrideInterfaceBase {
		function getTest():Object;
		function testMethod():void;
	}
}
