package test{
	import test.TestProxyInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestProxyInterface. Do not edit.
	 */
	public interface TestProxyInterface extends  test.TestProxyInterfaceBase {
		function baz(ago:Number):void;
	}
}