package expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestProxyInterfaceGeneric;
	/**
	 * Generated by CDoclet from TestProxyInterfaceBase.
	 * Do not edit.
	 */
	public interface TestProxyInterfaceBase extends  cdoclet.test.TestProxyInterfaceGeneric {
		override function foo(bar:Date):Array;
	}
}
