package expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestProxyInterfaceGeneric.
	 * Do not edit.
	 */
	public interface TestProxyInterfaceGeneric {
		function foo(bar:String):void;
	}
}
