package  expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestIgnoreInClassBase;
	/**
	 * Generated by CDoclet from TestIgnoreInClass.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestIgnoreInClass")]
	public class TestIgnoreInClass extends cdoclet.test.TestIgnoreInClassBase  {
		private var _test:Object;
		public override function get test():Object {
			return _test;
		}
		public override function set test(value:Object):void {
			_test=value;
		}
	}
}
