package test{
	import test.TestProxyInterfaceGeneric;
	/**
	 * Generated by CDoclet from test.TestProxyInterfaceBase.	 * Do not edit.
	 */
	public interface TestProxyInterfaceBase extends  test.TestProxyInterfaceGeneric {
		override function foo(bar:Date):Array;
	}
}