package  test{
	/**
	 * Generated by CDoclet from test.TestEnum. Do not edit.
	 */
	public final class TestEnum {
		public static const Right:String="Right";
		public static const Middle:String="Middle";
		public static const Left:String="Left";
	}
}