package test{
	import test.TestIgnoreInInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInInterface. Do not edit.
	 */
	public interface TestIgnoreInInterface extends  test.TestIgnoreInInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}