package  expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestIgnoreClass.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestIgnoreClass")]
	public class TestIgnoreClass {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}
