package  cdoclet.test{
	import cdoclet.test.TestIgnoreInClassBase;
	/**
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInClass.	 * Do not edit.
	 */
	[RemoteClass(alias="cdoclet.test.TestIgnoreInClass")]
	public class TestIgnoreInClass extends cdoclet.test.TestIgnoreInClassBase  {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}