package  cdoclet.test{
	import cdoclet.test.TestOverrideInterface;
	/**
	 * Generated by CDoclet from cdoclet.test.TestOverrideClassBase.	 * Do not edit.
	 */
	[RemoteClass(alias="cdoclet.test.TestOverrideClassBase")]
	public class TestOverrideClassBase implements cdoclet.test.TestOverrideInterface {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}