package asdoclet.test{
	import asdoclet.test.TestIgnoreInInterfaceBase;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInInterface.	 * Do not edit.
	 */
	public interface TestIgnoreInInterface extends  asdoclet.test.TestIgnoreInInterfaceBase {
		function getTest():Object;
		function testMethod():void;
	}
}