package  asdoclet.test{
	import asdoclet.test.TestOverrideClass;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreGeneric.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestIgnoreGeneric")]
	public class TestIgnoreGeneric extends asdoclet.test.TestOverrideClass  {
	}
}