package asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestProxyInterfaceGeneric.	 * Do not edit.
	 */
	public interface TestProxyInterfaceGeneric {
		function foo(bar:String):void;
	}
}