package  asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInClassBase.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestIgnoreInClassBase")]
	public class TestIgnoreInClassBase {
	}
}