package asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestInterfaceGeneric.	 * Do not edit.
	 */
	public interface TestInterfaceGeneric {
		function foo(bar:Date, baz:Object):void;
	}
}