package  asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreClass.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestIgnoreClass")]
	public class TestIgnoreClass {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}