package  asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestException.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestException")]
	public class TestException {
		private var _message:String;
		public function get message():String {
			return _message;
		}
		public function set message(value:String):void {
			_message=value;
		}
	}
}