package asdoclet.test{
	import asdoclet.test.TestProxyInterfaceBase;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestProxyInterface.	 * Do not edit.
	 */
	public interface TestProxyInterface extends  asdoclet.test.TestProxyInterfaceBase {
	}
}