package asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInterface.	 * Do not edit.
	 */
	public interface TestIgnoreInterface {
		function getTest():Object;
		function testMethod():void;
	}
}