package asdoclet.test{
	import asdoclet.test.TestProxyInterfaceGeneric;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestProxyInterfaceBase.	 * Do not edit.
	 */
	public interface TestProxyInterfaceBase extends  asdoclet.test.TestProxyInterfaceGeneric {
		override function foo(bar:Date):Array;
	}
}