package asdoclet.test{
	/**
	 * Generated by AsDoclet from asdoclet.test.TestOverrideInterfaceBase.	 * Do not edit.
	 */
	public interface TestOverrideInterfaceBase {
		function getTest():Object;
		function testMethod():void;
	}
}