package  asdoclet.test{
	import asdoclet.test.TestIgnoreInClassBase;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestIgnoreInClass.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestIgnoreInClass")]
	public class TestIgnoreInClass extends asdoclet.test.TestIgnoreInClassBase  {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}