package  asdoclet.test{
	import asdoclet.test.TestOverrideInterface;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestOverrideClassBase.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestOverrideClassBase")]
	public class TestOverrideClassBase implements asdoclet.test.TestOverrideInterface {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}