package  asdoclet.test{
	import asdoclet.test.TestOverrideClassBase;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestOverrideClass.	 * Do not edit.
	 */
	[RemoteClass(alias="asdoclet.test.TestOverrideClass")]
	public class TestOverrideClass extends asdoclet.test.TestOverrideClassBase  {
		private var _test:Object;
		public override function get test():Object {
			return _test;
		}
		public override function set test(value:Object):void {
			_test=value;
		}
	}
}