package asdoclet.test{
	import asdoclet.test.TestOverrideInterfaceBase;
	/**
	 * Generated by AsDoclet from asdoclet.test.TestOverrideInterface.	 * Do not edit.
	 */
	public interface TestOverrideInterface extends  asdoclet.test.TestOverrideInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}