package  testactionscript{
	import testactionscript.TestOverrideInterface;
	/**
	 * Generated by CDoclet from test.TestOverrideClassBase. Do not edit.
	 */
	[RemoteClass(alias="testactionscript.TestOverrideClassBase")]
	public class TestOverrideClassBaseDto implements testactionscript.TestOverrideInterface {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}