package  testactionscript{
	import testactionscript.TestOverrideClass;
	/**
	 * Generated by CDoclet from test.TestIgnoreGeneric. Do not edit.
	 */
	[RemoteClass(alias="testactionscript.TestIgnoreGenericDto")]
	public class TestIgnoreGenericDto extends testactionscript.TestOverrideClass  {
	}
}