package testactionscript{
	import testactionscript.TestBean;
	import testactionscript.TestProxyInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestProxyInterface. Do not edit.
	 */
	public interface TestProxyInterface extends  testactionscript.TestProxyInterfaceBase {
		function baz(ago:Number):testactionscript.TestBean;
	}
}