package  testactionscript{
	import testactionscript.TestIgnoreInClassBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInClass. Do not edit.
	 */
	[RemoteClass(alias="testactionscript.TestIgnoreInClass")]
	public class TestIgnoreInClassDto extends testactionscript.TestIgnoreInClassBase  {
		private var _test:Object;
		public override function get test():Object {
			return _test;
		}
		public override function set test(value:Object):void {
			_test=value;
		}
	}
}