package testactionscript{
	import testactionscript.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestOverrideInterface. Do not edit.
	 */
	public interface TestOverrideInterface extends  testactionscript.TestOverrideInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}