package testactionscript{
	import testactionscript.TestIgnoreInInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInInterface. Do not edit.
	 */
	public interface TestIgnoreInInterface extends  testactionscript.TestIgnoreInInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}