package  testactionscript{
	import testactionscript.TestOverrideClassBase;
	/**
	 * Generated by CDoclet from test.TestOverrideClass. Do not edit.
	 */
	[RemoteClass(alias="testactionscript.TestOverrideClass")]
	public class TestOverrideClassDto extends testactionscript.TestOverrideClassBase  {
		private var _test:Object;
		public override function get test():Object {
			return _test;
		}
		public override function set test(value:Object):void {
			_test=value;
		}
	}
}