package  testactionscript{
	/**
	 * Generated by CDoclet from test.TestException. Do not edit.
	 */
	[RemoteClass(alias="testactionscript.TestExceptionDto")]
	public class TestExceptionDto {
		private var _message:String;
		public function get message():String {
			return _message;
		}
		public function set message(value:String):void {
			_message=value;
		}
	}
}