package testactionscript{
	import testactionscript.TestProxyInterfaceGeneric;
	/**
	 * Generated by CDoclet from test.TestProxyInterfaceBase. Do not edit.
	 */
	public interface TestProxyInterfaceBase extends  testactionscript.TestProxyInterfaceGeneric {
		override function foo(bar:Date):Array;
	}
}