package testactionscript{
	import testactionscript.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from test.TestIgnoreInInterfaceBase. Do not edit.
	 */
	public interface TestIgnoreInInterfaceBase extends  testactionscript.TestOverrideInterfaceBase {
	}
}