package  expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestOverrideInterface;
	/**
	 * Generated by CDoclet from TestOverrideClassBase.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestOverrideClassBase")]
	public class TestOverrideClassBase implements cdoclet.test.TestOverrideInterface {
		private var _test:Object;
		public function get test():Object {
			return _test;
		}
		public function set test(value:Object):void {
			_test=value;
		}
	}
}
