package expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestIgnoreInterface.
	 * Do not edit.
	 */
	public interface TestIgnoreInterface {
		function getTest():Object;
		function testMethod():void;
	}
}
