package expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestProxyInterfaceBase;
	/**
	 * Generated by CDoclet from TestProxyInterface.
	 * Do not edit.
	 */
	public interface TestProxyInterface extends  cdoclet.test.TestProxyInterfaceBase {
	}
}
