package expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestOverrideInterfaceBase;
	/**
	 * Generated by CDoclet from TestOverrideInterface.
	 * Do not edit.
	 */
	public interface TestOverrideInterface extends  cdoclet.test.TestOverrideInterfaceBase {
		override function getTest():Object;
		override function testMethod():void;
	}
}
