package expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestInterfaceGeneric.
	 * Do not edit.
	 */
	public interface TestInterfaceGeneric {
		function foo(bar:Date, baz:Object):void;
	}
}
