package  expectations.as.cdoclet.test{
	import expectations.as.cdoclet.test.TestOverrideClassBase;
	/**
	 * Generated by CDoclet from TestOverrideClass.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestOverrideClass")]
	public class TestOverrideClass extends cdoclet.test.TestOverrideClassBase  {
		private var _test:Object;
		public override function get test():Object {
			return _test;
		}
		public override function set test(value:Object):void {
			_test=value;
		}
	}
}
