package  expectations.as.cdoclet.test{
	/**
	 * Generated by CDoclet from TestException.
	 * Do not edit.
	 */
	[RemoteClass(alias="TestException")]
	public class TestException {
		private var _message:String;
		public function get message():String {
			return _message;
		}
		public function set message(value:String):void {
			_message=value;
		}
	}
}
