

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestOverrideBean.
	 * Do not edit.
 */
public class TestOverrideBean extends TestBean {
	private long count;

	public long getCount() {
		return this.count;
	}

	public void setCount(long value) {
		this.count = value;
	}
}
