

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestOverrideInterface.
	 * Do not edit.
 */
public interface TestOverrideInterface<T> extends TestOverrideInterfaceBase<T> {
	T getTest();
	void testMethod();
}
