

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestIgnoreInClassBase.
	 * Do not edit.
 */
public class TestIgnoreInClassBase<T> {
	private T test;

	public T getTest() {
		return this.test;
	}

	public void setTest(T value) {
		this.test = value;
	}
}
