

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestProxyInterfaceBase.
	 * Do not edit.
 */
public interface TestProxyInterfaceBase<T extends java.util.Date> extends TestProxyInterfaceGeneric {
	java.util.Collection<T> foo(T bar);
}
