

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestBean.
	 * Do not edit.
 */
public class TestBean {
	private int value;
	private String name;

	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String value) {
		this.name = value;
	}
}
