

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestOverrideInterfaceBase.
	 * Do not edit.
 */
public interface TestOverrideInterfaceBase<T> {
	T getTest();
	void testMethod();
}
