

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestIgnoreInClass.
	 * Do not edit.
 */
public class TestIgnoreInClass<T> extends TestIgnoreInClassBase<T> {

	@Override
	public T getTest() {
		return super.getTest();
	}

	@Override
	public void setTest(T value) {
		super.setTest(value);
	}
}
