

package expectations.java.cdoclet.test;
/**
 * Generated by CDoclet from TestInterfaceAnnotations.
	 * Do not edit.
 */
@Deprecated
public interface TestInterfaceAnnotations {
	@Deprecated
	void annotatedMethod();
	void notAnnotatedMethod();
}
