

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestOverrideClassBase.	 * Do not edit.
	 * </summary>
	 */
	public class TestOverrideClassBase<T> : cdoclet.test.TestOverrideInterface<T> {
		private T test;
		public virtual T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}