

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestOverrideClass.	 * Do not edit.
	 * </summary>
	 */
	public class TestOverrideClass<T> : cdoclet.test.TestOverrideClassBase<T> {
		public override T Test { get { return this.test; } set { this.test = value; } }
	}
#endregion
}