

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestIgnoreInClassBase.	 * Do not edit.
	 * </summary>
	 */
	public class TestIgnoreInClassBase<T> {
	}
#endregion
}