

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestProxyInterface.	 * Do not edit.
	 * </summary>
	 */
	public interface TestProxyInterface : cdoclet.test.TestProxyInterfaceBase<java.sql.Date> {
	}
#endregion
}