

namespace cdoclet.test {
#region CDoclet generated code
	/**
	 * <summary>
	 * Generated by CDoclet from cdoclet.test.TestException.	 * Do not edit.
	 * </summary>
	 */
	public class TestException : System.Exception {
		public  TestException()  : base() {}
		public  TestException(string message)  : base(message) {}
		public  TestException(string message, System.Exception exception)  : base(message, exception) {}
	}
#endregion
}